// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ-LN79DTVEMG6fNV74nt8Mc--j2VE2jM',
    appId: '1:769259629235:web:3cb0485e4db8d1cda35ec6',
    messagingSenderId: '769259629235',
    projectId: 'ecommerceapp-fd45f',
    authDomain: 'ecommerceapp-fd45f.firebaseapp.com',
    storageBucket: 'ecommerceapp-fd45f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmJkgFiFMN6LLxa9GkJmDvvxPxYisDdqE',
    appId: '1:769259629235:android:349716c51bc04b01a35ec6',
    messagingSenderId: '769259629235',
    projectId: 'ecommerceapp-fd45f',
    storageBucket: 'ecommerceapp-fd45f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDyuUZf6BKhdzaRAYwgygKXf4j3hYLU8k',
    appId: '1:769259629235:ios:9d0ab2f546f9fe45a35ec6',
    messagingSenderId: '769259629235',
    projectId: 'ecommerceapp-fd45f',
    storageBucket: 'ecommerceapp-fd45f.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDyuUZf6BKhdzaRAYwgygKXf4j3hYLU8k',
    appId: '1:769259629235:ios:9d0ab2f546f9fe45a35ec6',
    messagingSenderId: '769259629235',
    projectId: 'ecommerceapp-fd45f',
    storageBucket: 'ecommerceapp-fd45f.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ-LN79DTVEMG6fNV74nt8Mc--j2VE2jM',
    appId: '1:769259629235:web:0ee34b49f2605f4fa35ec6',
    messagingSenderId: '769259629235',
    projectId: 'ecommerceapp-fd45f',
    authDomain: 'ecommerceapp-fd45f.firebaseapp.com',
    storageBucket: 'ecommerceapp-fd45f.appspot.com',
  );
}
