name: global
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none
environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  dio: 
  logger:
  flutter_screenutil: 
  go_router: 
  google_fonts: ^5.1.0
  flutter_riverpod: 
  flutter_svg: 
  carousel_slider: 
  smooth_page_indicator: ^1.0.0+2
  http:
  jwt_decoder:
  firebase_auth: ^4.14.0
  hasura_connect: ^5.0.0+3
  shared_preferences: ^2.2.2
  pinput: ^4.0.0
  path_provider: ^2.1.3
  flutter_card_swiper: ^7.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  permission_handler: ^11.3.1
  dob_input_field: ^2.0.0
  location: ^5.0.0
  geolocator: ^11.0.0
  cloud_firestore:  
  # insta_assets_picker:
  image_picker: 
  # flutter_multi_formatter: ^2.12.4
  # flutter_masked_text: ^4.0.0-nullsafety
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


